In [6]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter, FuncFormatter
import datetime as dt

pd.set_option('display.max_columns', 15)
pd.set_option('display.max_rows', 50)
pd.options.display.float_format = '{:,.4f}'.format

%matplotlib inline
plt.rcParams['figure.figsize'] = (8, 6)
plt.style.use("fivethirtyeight")

# Makes graphs crisp. Only use if you don't have a lot of points/lines on your graph.
%config InlineBackend.figure_formats = ['svg', 'retina'] # use svg, then retina if svg is not supported

In [7]:
helper_dir = '../helper'

%run {helper_dir}/defillama.py
%run {helper_dir}/plot.py

In [8]:
obj = DefiLlama()

In [4]:
# say we're interested in getting the prices of the following tokens from the corresponding chains/sources
dd = {'0xdF574c24545E5FfEcb9a659c229253D4111d87e1':'ethereum',
      'ethereum':'coingecko',
      '0x762539b45a1dcce3d36d080f74d1aed37844b878':'bsc',
      '0xdB25f211AB05b1c97D595516F45794528a807ad8':'ethereum',
      '0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a':'arbitrum',  # GMX on arbitrum
      '0x62edc0692BD897D2295872a9FFCac5425011c661':'avax',      # GMX on avalanche
      '0x4277f8f2c384827b5273592ff7cebd9f2c1ac258':'arbitrum',  # GLP on arbitrum
      '0x01234181085565ed162a948b6a5e88758CD7c7b8':'avax',      # GLP on avalanche
      }

## Get current prices of tokens by contract address

In [7]:
obj.get_tokens_curr_prices(dd)

,timestamp,symbol,price,confidence,chain,token_address,decimals
0,2022-09-25 02:00:26,GLP,0.7313,1.0000,avax,0x01234181085565ed162a948b6a5e88758CD7c7b8,18.0000
1,2022-09-25 02:32:53,ETH,"1,318.6600",0.9900,coingecko,ethereum,NaN
2,2022-09-25 02:00:27,GLP,0.8827,1.0000,arbitrum,0x4277f8f2c384827b5273592ff7cebd9f2c1ac258,18.0000
3,2022-09-25 02:32:51,GMX,39.5800,0.9900,arbitrum,0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a,18.0000
4,2022-09-25 02:32:51,GMX,39.5800,0.9900,avax,0x62edc0692BD897D2295872a9FFCac5425011c661,18.0000
5,2022-09-25 02:32:52,HUSD,0.9924,0.9900,ethereum,0xdF574c24545E5FfEcb9a659c229253D4111d87e1,8.0000
6,2022-09-25 02:32:56,EURS,0.9597,0.9900,ethereum,0xdB25f211AB05b1c97D595516F45794528a807ad8,2.0000
7,2022-09-25 02:32:53,LINA,0.0071,0.9900,bsc,0x762539b45a1dcce3d36d080f74d1aed37844b878,18.0000

## Get snapshot historical prices of tokens by contract address

In [8]:
obj.get_tokens_hist_snapshot_prices(dd, '2022-09-15 13:25:43')

,timestamp,symbol,price,chain,token_address,decimals
0,2022-09-15 13:00:25,GLP,0.7712,avax,0x01234181085565ed162a948b6a5e88758CD7c7b8,18.0000
1,2022-09-15 13:23:16,EURS,0.9900,ethereum,0xdB25f211AB05b1c97D595516F45794528a807ad8,2.0000
2,2022-09-15 13:25:07,GMX,46.6015,arbitrum,0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a,18.0000
3,2022-09-15 13:26:40,ETH,"1,586.8219",coingecko,ethereum,NaN
4,2022-09-15 13:23:24,LINA,0.0079,bsc,0x762539b45a1dcce3d36d080f74d1aed37844b878,18.0000
5,2022-09-15 13:25:07,GMX,46.6015,avax,0x62edc0692BD897D2295872a9FFCac5425011c661,18.0000
6,2022-09-15 13:00:25,GLP,0.9223,arbitrum,0x4277f8f2c384827b5273592ff7cebd9f2c1ac258,18.0000
7,2022-09-15 13:23:50,HUSD,0.9943,ethereum,0xdF574c24545E5FfEcb9a659c229253D4111d87e1,8.0000

In [10]:
obj.get_tokens_hist_snapshot_prices(dd, '2020-09-15 13:25:43')

,timestamp,symbol,price,chain,token_address,decimals
0,2020-09-15 13:03:12,HUSD,1.0012,ethereum,0xdF574c24545E5FfEcb9a659c229253D4111d87e1,8.0000
1,2020-09-15 13:13:07,EURS,1.1774,ethereum,0xdB25f211AB05b1c97D595516F45794528a807ad8,2.0000
2,2020-09-15 13:06:08,ETH,377.5982,coingecko,ethereum,NaN

## Get daily close ('23:59:59') prices of tokens by contract address

They don't offer an API for bulk downloading historical data at the moment. It's slow to iteratively call the historical snapshot price API.

In [11]:
# start = dt.date(2022, 1, 1)
# end   = dt.date(2022, 9, 25)
# dates = pd.date_range(start, end)
# dttms = [date.replace(hour=23, minute=59, second=59) for date in dates]
# dttms

## Get the closest block to a timestamp

In [11]:
obj.get_closest_block('ethereum', '2020-09-24 13:25:43')
# height: number of blocks before the returned block
# timestamp: timestamp of the returned block since the epoch

     height           timestamp
0  10925595 2020-09-24 13:25:30